### ISSUE TITLE
Can't build it on CentOS 7 x64

### ISSUE THREAD

**Issue by versluis** [tessus/apachetop#1]
Hello team!

I've been trying to build apachetop on CentOS 7 x64, and somehow it doesn't want to do it. I have both readline-devel and ncurses-devel installed, but configure tells me that the C++ compiler cannot build executables.

What might I be doing wrong?

**Comment by tessus** [comment]
You are most likely missing something in the toolchain.

Try to install all necessary g++ tools: `yum install  gc gcc++ *gcc-c++*`

If this does not help, look at the output in `config.log`. This usually tells you what the problem is.

**Comment by versluis** [comment]
Thank you so much, it was indeed the gcc++ package that wasn't installed! 
Much appreciated!
I love apachetop ;-)
