### ISSUE TITLE
Switch from obsolete PCRE 8.x to current PCRE2 10.x?

### ISSUE THREAD

**Issue by robert-scheck** [tessus/apachetop#12]
The PCRE library is at end of life, and is no longer being actively maintained, (new) projects should use PCRE2 instead.

See also:
  - https://www.pcre.org/
  - https://bugzilla.redhat.com/show_bug.cgi?id=2128271

Do you see any chance to switch from obsolete PCRE 8.x to current PCRE2 10.x?

**Comment by tessus** [comment]
I think I can make this work, unless pcre2 is completely different than pcre. I haven't touched this code for years and I have only done maintenance. I am not the original author of apachetop.
I have more time in October and will check it out then.

**Comment by tessus** [comment]
@robert-scheck Sorry that it took so long. There was always something...

Can you please try the following branch? https://github.com/tessus/apachetop/tree/feature/pcre2

or PR #14

**Comment by tessus** [comment]
Hmm, something doesn't seem right. I have to do more testing.
