### ISSUE TITLE
apachetop 0.23.2 build failure on ubuntu-22.04

### ISSUE THREAD

**Issue by chenrui333** [tessus/apachetop#16]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
/usr/bin/ld: apachetop.o: in function `main':
apachetop.cc:(.text.startup+0x152): undefined reference to `adns_init'
/usr/bin/ld: log.o: in function `CommonLogParser::parse(char*, logbits*)':
log.cc:(.text+0x534): undefined reference to `adns_submit_reverse'
/usr/bin/ld: log.cc:(.text+0x5c3): undefined reference to `adns_submit'
/usr/bin/ld: log.o: in function `collect_dns_responses()':
log.cc:(.text+0x6eb): undefined reference to `adns_check'
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4234179211/jobs/7356279516
relates to Homebrew/homebrew-core#123852

**Comment by tessus** [comment]
This error seems to be brew related. I don't use homebrew, thus can't help. But it seems that brew builds with adns but without adns libraries/includes. Not sure how this is even possible.

I have built apachetop on macOS (macports) and on several Linux flavors by using configure/make.

If you send me a `config.log` (created by configure), and the output of `make` I might be able to help.

I suggest you try building it as described in the [INSTALL](https://github.com/tessus/apachetop/blob/master/INSTALL) file. If you run into an issue with brew, please report it to the brew maintainers.

**Comment by chenrui333** [comment]
@tessus sorry for the noise, yeah, it is indeed the bottle issue for adns, which is fixed by [a rebuild](https://github.com/Homebrew/homebrew-core/commit/b7749dedca5ea8781e97902447a26654b78fc2fd). Thanks for bearing with me on this. :)

**Comment by tessus** [comment]
no worries. I am glad that you were able to fix the issue.
